---
kind: pipeline
name: default
platform:
  os: linux
  arch: arm64

steps:
- name: test
  image: python
  commands:
  - pip install -r requirements.txt
  - python -m unittest tests/*

---
kind: pipeline
type: kubernetes
name: default

steps:
- name: test
  image: python
  commands:
  - pip install -r requirements.txt
  - python -m unittest tests/*
